name: Deploy to DEV
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Generate Build and Deploy to DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'  # Specify the Node.js version
 
      - name: Copy .env file
        env:
         ENV_FILE_CONTENT: ${{ secrets.env }}
        run: echo "$ENV_FILE_CONTENT" > .env

   
      - name: Install Angular CLI and Dependencies
        run: |
          npm install -g @angular/cli@^10.0.0
          npm install --legacy-peer-deps

      - name: Generate env.ts
        run: node src/set-env.js
        
      - name: Generate Angular Build
        run: |
          ng build --prod
          npm run build --prod

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}

      - name: Set up SSH key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         # Add the SSH key to the known_hosts file (replace hostname with your actual hostname)
         ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
           rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./dist/sunbird-rc-ui/ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/dev.educert.ng/public


      - name: Show PWD
        run: |
           echo "Current Working Directory:"
           pwd
           echo "Angular version:"
           ng version
           echo "npm version   "
           npm -v

      - name: List Contents
        run: |
           echo "Contents of the current directory (in reverse order):"
           ls -lr
